In [6]:
import torch

x = torch.tensor([[[1,2],[3,4]],[[5,6],[7,8]]])
print(x)
weight = torch.tensor([[1,1],[2,2]])
print(weight)
print(weight.unsqueeze(1))
result = weight.unsqueeze(1).bmm(x)

print(result)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
tensor([[1, 1],
        [2, 2]])
tensor([[[1, 1]],

        [[2, 2]]])
tensor([[[ 4,  6]],

        [[24, 28]]])


In [20]:
alpha = torch.ones(x.size(0), x.size(1))
print(alpha.sum(0).expand(alpha.size()))

print(x.data.eq(1).float())

print(x.size(-1))
x_flat = x.view(-1, x.size(-1))
print(x_flat)

import torch.nn.functional as F
alpha.data.masked_fill_(x_flat)
alpha = F.softmax(x_flat,dim=-1)
print(alpha)

tensor([[2., 2.],
        [2., 2.]])
tensor([[[1., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])
2
tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


RuntimeError: "softmax_lastdim_kernel_impl" not implemented for 'Long'

In [3]:
import torch

dir(torch)
help(torch.cuda.is_available)

Help on function is_available in module torch.cuda:

is_available() -> bool
    Returns a bool indicating if CUDA is currently available.

